[theme]
# Primary accent color for interactive elements.
#primaryColor = "#d33682" # Pink red color

# Background color for the main content area.
#backgroundColor = "#002b36" # Dark purple color

# Background color used for the sidebar and most interactive widgets.
#secondaryBackgroundColor = "#586e75" # Moderate dark grey color

# Color used for almost all text.
#textColor = "#fafafa" # Like white color

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"